module.exports = {
  COMMUNITY_VOITING: 'COMMUNITY_VOITING',
  USER_CONNECTED: 'USER_CONNECTED',
  VOICE_RECIEVED: 'VOICE_RECIEVED',
  VOITING_SENT: 'VOITING_SENT',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  START_VOITING: 'START_VOITING',
  STOP_VOITING: 'STOP_VOITING'
};
